  
---
deployment:
      tasks:
        - export DEPLOYPATH=/home/mootenso/public_html/mootens
        - /bin cp * $DEPLOYPATH
        - /bin/cp -r * $DEPLOYPATH
        - /bin/cp index.html $DEPLOYPATH-
        - /bin/cp -R images $DEPLOYPATH
